a = input('Digite qualquer coisa: ')
print('O tipo primitivo desse valor é', type(a))
print('É um número?', a.isnumeric())
print('É um alfabético?', a.isalpha())
print('Está no sistema ASCII ou está vazia?', a.isascii())
print('É um dígito?', a.isdigit())
print('Está em minúsculas?', a.islower())
print('É um dígito?', a.isidentifier())
print('É um decimal?', a.isdecimal())
print('É vísivel?', a.isprintable())
print('Está em maiúsculas?', a.isupper())
print('EStá capitalizado?', a.istitle())
print('É somente espaço?', a.isspace())
print('É um alfanúmero?', a.isalnum())
